export const FETCH_PRODUCTS = "FETCH_PRODUCTS";
export const FETCH_PRODUCTS_SUCCESS = "FETCH_PRODUCTS_SUCCESS";
export const FETCH_PRODUCT = "FETCH_PRODUCT";
export const FETCH_PRODUCT_SINGLE = "FETCH_PRODUCT_SINGLE";
export const SET_CATEGORY_FILTER = "SET_CATEGORY_FILTER";
export const FETCH_CATEGORIES = "ADD_CATEGORIES";

export const ADD_TO_CART = "ADD_TO_CART";
export const REMOVE_FROM_CART = "REMOVE_FROM_CART";
